databases:
  - name: dashbord
    databaseName: dashbord
    user: dashbord_user

services:
  - type: web
    name: dashbord
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dashbord
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false